spring:
  application:
    name: onmoim
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL} # jdbc:mysql://localhost:3306/{데이터베이스명}
    username: ${DB_USER} # MySQL 유저 이름
    password: ${DB_PW} # MySQL 비밀번호
  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: none # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  # 메일 발송 설정
  mail:
    host: smtp.gmail.com
    port: 587
    accounts:
      - username: "${MAIL_USERNAME_1}"
        password: "${MAIL_PASSWORD_1}"
      - username: "${MAIL_USERNAME_2}"
        password: "${MAIL_PASSWORD_2}"
    properties:
      mail.smtp.auth: "true"
      mail.smtp.starttls.enable: "true"
      mail.smtp.ssl.trust: "smtp.gmail.com"

  cloudflare:
    turnstile:
      secret-key: ${TURNSTILE_SECRET_KEY}
      verify-url: https://challenges.cloudflare.com/turnstile/v0/siteverify